"""add user_id column to translation model

Revision ID: 3b7429db4f6c
Revises: fd726c82e915
Create Date: 2021-11-28 01:32:20.332321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7429db4f6c'
down_revision = 'fd726c82e915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_translation_user_id', 'translation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_translation_user_id', 'translation', type_='foreignkey')
    op.drop_column('translation', 'user_id')
    # ### end Alembic commands ###
