"""add suggestion model

Revision ID: 5cb384e57dfa
Revises: 2332328ce76a
Create Date: 2021-11-24 02:16:41.563207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb384e57dfa'
down_revision = '2332328ce76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    # ### end Alembic commands ###
