"""translation model

Revision ID: 88c5b7aeb2ea
Revises: 
Create Date: 2021-11-15 16:07:59.378974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c5b7aeb2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_language', sa.String(length=50), nullable=True),
    sa.Column('output_language', sa.String(length=50), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_on', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    # ### end Alembic commands ###
