"""add language helper model

Revision ID: 916fb0b72d80
Revises: bac84af575c7
Create Date: 2021-12-19 00:54:07.107608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916fb0b72d80'
down_revision = 'bac84af575c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_helper',
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('language')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_helper')
    # ### end Alembic commands ###
