"""add status helper model

Revision ID: b07981abb72b
Revises: bac84af575c7
Create Date: 2021-12-05 01:04:58.814448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07981abb72b'
down_revision = 'bac84af575c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_helper',
    sa.Column('input_language', sa.String(length=50), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('input_language')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_helper')
    # ### end Alembic commands ###
