"""add user_id column to suggestion model

Revision ID: bac84af575c7
Revises: 3b7429db4f6c
Create Date: 2021-11-28 01:43:00.378447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bac84af575c7'
down_revision = '3b7429db4f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('suggestion', 'suggested_text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('suggestion', 'translation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key('fk_suggestion_user_id', 'suggestion', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_suggestion_user_id', 'suggestion', type_='foreignkey')
    op.alter_column('suggestion', 'translation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('suggestion', 'suggested_text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('suggestion', 'user_id')
    # ### end Alembic commands ###
